# Generated by Django 5.2.8 on 2025-12-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Post",
        ),
    ]
