# Generated by Django 5.2.8 on 2025-12-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="Избражение"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tresh",
            field=models.TextField(
                blank=True, max_length=100000, null=True, verbose_name="Содержимое"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
