# Generated by Django 5.2.8 on 2025-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image_alter_post_tresh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Количество просмотров"
            ),
        ),
    ]
